### ISSUE TITLE
Refreshing connection pool after all connections used/used as singleton model

### ISSUE THREAD

**Issue by d-m-cc** [kostya/redisoid#3]
Hello,
I'm just beginning to explore the world of Crystal programming, so please excuse me if I make any rudimentary mistakes!
The scenario I've set up is that I have a web server with incoming requests, using Redisoid with a pool to connect to a Redis server.

I'm experimenting with stopping and restarting the Redis server, and I'm wondering how to force Redisoid to attempt to reconnect to the Redis server after all the connections in the connection pool have been exhausted.

For example, I have Redisoid initialized:
```
Redisoid.new(url: "redis://127.0.0.1:6379", pool: 10)
```

- When I request the endpoint (which retrieves a key) with the Redis server running, the key is returned **(expected)**
- When I request the endpoint after quitting the Redis server, I get a `ERROR: Closed stream (IO::Error)` **(expected)**
- When I request the endpoint after restarting the Redis server, I continue to get the `ERROR: Closed stream (IO::Error)` message **(unexpected?)**

My initial impression would be that it should attempt to reconnect to redis or refresh the connection pool, but even though the Redis server is accepting connections, Redisoid continues to return `IO::Error`. This will persist until I completely restart the web server (Lucky).

The result of this in the case of a web server is that even when the Redis server comes back up, future requests will continue to fail until the web server itself is restarted. I would hope that once the Redis server is available again, the requests could resume successfully.

To share more context (sorry for the long message!), here's my (singleton) model in Lucky:
```
class RedisService
  INSTANCE = new

  @client : Redisoid?

  private def initialize
  end

  def client : Redisoid
    @client ||= Redisoid.new(url: "redis://127.0.0.1:6379", pool: 10)
  end

  def getkey
    INSTANCE.client.get("bla")
  end
end
```
And I call it like so:
```
RedisService::INSTANCE.getkey
```
At this point I'm unsure as to whether the cause of not reconnecting is the logic in Redisoid or because the singleton model does not re-instantiate the Redisoid object once it is created. I can short circuit it (and make it work) with the following, but it feels like bad practice and a code smell!

```
class RedisService
  INSTANCE = new

  Habitat.create do
    setting url : String
    setting pool : Int32
  end

  @client : Redisoid?

  private def initialize
  end

  def client : Redisoid
    @client ||= Redisoid.new(url: "redis://127.0.0.1:6379", pool: 10)
  end

  def getkey
    begin
      INSTANCE.client.get("bla")
    rescue IO::Error
      @client = Redisoid.new(url: "redis://127.0.0.1:6379", pool: 10)
      INSTANCE.client.get("bla")
    end
  end
end
```
Thanks for any thoughts!

**Comment by kostya** [comment]
redisoid only reconnects on Redis::DisconnectedError, so if after restart redis server, client gets IO::Error instead of Redis::DisconnectedError, this is a bug in https://github.com/stefanwille/crystal-redis

**Comment by kostya** [comment]
or we can also add reconnect on IO::Error closed stream

**Comment by d-m-cc** [comment]
Thank you @kostya ! I created an issue for crystal-redis 😄
